### ISSUE TITLE
翻译认领：wiki/Manual.md #Exchange Structure

### ISSUE THREAD

**Issue by echo-ray** [bilibilihuangyifan/ccxtcn#19]
[wiki/Manual.md #Exchange Structure](https://github.com/ccxt/ccxt/wiki/Manual#exchange-structure)

**Comment by echo-ray** [comment]
如果没有朋友已经翻译了这部分的话，那我就慢慢开动这部份文档了？

**Comment by bilibilihuangyifan** [comment]
#25
