### ISSUE TITLE
翻译认领：wiki/Install.md

### ISSUE THREAD

**Issue by bilibilihuangyifan** [bilibilihuangyifan/ccxtcn#2]
链接： [Install.md](https://github.com/bilibilihuangyifan/ccxtcn/blob/CN-TRANSLATION/wiki/Install.md)

**Comment by cmy00cmy** [comment]
认领，可以直接编辑md吗？

**Comment by bilibilihuangyifan** [comment]
最好新建一个CN-开头的文件

**Comment by echo-ray** [comment]
@cmy00cmy 前面的部分可以直接参考 CN-README.md 的一部分哈

**Comment by bilibilihuangyifan** [comment]
翻译完成，感谢@cmy00cmy 的辛苦工作！
