### ISSUE TITLE
翻译认领：README.md

### ISSUE THREAD

**Issue by bilibilihuangyifan** [bilibilihuangyifan/ccxtcn#5]
链接：[README.md](https://github.com/bilibilihuangyifan/ccxtcn/blob/CN-TRANSLATION/README.md)

**Comment by echo-ray** [comment]
readme差不多完成了，这五个内容比较多重复的。想承包一下

**Comment by bilibilihuangyifan** [comment]
欢迎👏，README的内容可以覆盖其余几个
